# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
controller:
  image: "jenkins/jenkins"
  tag: "2.361.2-jdk11"
  # tagLabel: jdk11
  serviceType: LoadBalancer
  loadBalancerSourceRanges:
  - 103.214.138.52/32
  installPlugins:
    - kubernetes:3706.vdfb_d599579f3
    - git:4.11.5
    - configuration-as-code:1512.vb_79d418d5fc8
    - workflow-aggregator:590.v6a_d052e5a_a_b_5
