# Image for Jenkins slave with all packages pre-installed
from jenkinsci/jnlp-slave
#from jenkins/jnlp-slave:3.27-1-alpine


USER root
RUN apt-get update && apt-get install -y maven
RUN apt-get install -y net-tools iputils-ping
RUN apt-get install -y curl wget vim openssh-server sshpass


USER jenkins
